# Generated by Django 3.2.25 on 2024-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/images/'),
        ),
    ]
