# Generated by Django 3.2.25 on 2024-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240628_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favimage',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/images/'),
        ),
    ]
