# Generated by Django 3.2.25 on 2024-06-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_favimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pulished_date',
            new_name='published_date',
        ),
    ]
